[alembic]
script_location = migrations
sqlalchemy.url = postgresql://username:password@localhost:5432/mydatabase
script_location = migrations
[loggers]
keys = root,sqlalchemy,pyramid
[handlers]
keys = console
[formatters]
keys = generic
[logger_root]
level = WARN
handlers = console
[logger_sqlalchemy]
level = INFO
handlers = console
qualname = sqlalchemy.engine
[handler_console]
class = StreamHandler
args = []
level = DEBUG
formatter = generic
[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s